name: Production deployment

on: 
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: rg-cd-with-actions
  AZURE_APP_PLAN: plan-actions-ttt-deployment
  AZURE_LOCATION: '"East US 2"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: YRollHid-ttt-app
  #################################################